### ISSUE TITLE
Mod incompatibility 1.19.2

### ISSUE THREAD

**Issue by 0username2bf** [Paspartout/UntitledDuckMod#69] opened 2022-08-22 01:05 UTC
**Describe the bug**
There seems to be an incompatibility between this mod and one or several other mods I have installed that prevents the game from launching. I'm unable to diagnose which mod it might be, but I figured making a bug report with an error log could be wise.

**Version**
Untitled Duck Mod v0.6.0, Fabric 1.19.2, latest Fabric API 0.60.0

**Error Log**
https://gist.github.com/0username2bf/8156190e29e421e683063ebd92e3ee3c

Apologies if irrelevant.

**Comment by Timolino456** [comment] 2022-08-28 15:53
Can confirm this, I am getting the same error when trying to use it either in my modpack or even when trying it with only Fabric API and Geckolib installed.

**Comment by Okabintaro** [comment] 2022-08-28 16:35
I think I know what the problem is, will fix it asap, thanks for the report!
It has to do with how I implemented the spawning mechanism which changed in fabric-api 0.60.

**Comment by Okabintaro** [comment] 2022-09-02 19:15
Thanks for the report! Should be fixed now in 0.6.1!

**Closed as completed by Okabintaro** 2022-09-02 19:15 UTC
Labels: bug

**Comment by 0username2bf** [comment] 2022-09-03 07:44
Awesome! And np!
